name: FunFact

on:
  workflow_dispatch:
  schedule:
    - cron: '26 1 * * *'

jobs:
  update-readme:
    name: FunFact
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
        with:
          COMMIT_MESSAGE: Quote Updated.
          OPTION: funfact