name: Quote README

on:
  workflow_dispatch:
  schedule:
    - cron: '* 6 * * *'

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
        with:
          COMMIT_MESSAGE: Quote Updated
          OPTION: funfact