name: Update Timestamp

on:  
  schedule:
    - cron: '* 2 * * *'
  workflow_dispatch:

jobs:
  activity:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add activity to readme
        uses: Readme-Workflows/recent-activity@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}